on : [workflow_dispatch]

jobs: 
 custom-js-action-job:
 
  runs-on : ubuntu-latest
  
  name : Custom JS gitHub Action
  
  steps:
    - name : First GitHub Custom Action 
      id : myjsaction
      uses: adilshehzad786/Timestamp-Action@v1
      with:
       name-of-you : 'Adil'
    
    - name : Output of the TimeStamp
      run : echo "The time was project is ${{steps.myjsaction.outputs.time}}"
     
     
    
 
    
    
  
